from tools.openairequest import OpenAIRequest


class MockOpenAI(OpenAIRequest):
    def call(self):
        return {
            "WEDDING_SUBCATEGORY_WEDDING_VENUES": 2000,
            "WEDDING_SUBCATEGORY_CATERING": 15300,
            "WEDDING_SUBCATEGORY_LAWYER": 150,
            "WEDDING_SUBCATEGORY_PHOTOGRAPHER": 1700,
            "WEDDING_SUBCATEGORY_VIDEOGRAPHER": 1300,
            "WEDDING_SUBCATEGORY_DEEJAY": 1050,
            "WEDDING_SUBCATEGORY_FLOWERS": 800,
            "WEDDING_SUBCATEGORY_BRIDE_DRESS": 1000,
            "WEDDING_SUBCATEGORY_GROOM_SUITS": 400,
            "WEDDING_SUBCATEGORY_GUEST_INVITATIONS": 200,
            "WEDDING_SUBCATEGORY_MAKEUP_BRIDE": 250,
            "WEDDING_SUBCATEGORY_HAIR_SALON_BRIDE": 250,
            "WEDDING_SUBCATEGORY_BAKERY": 300,
            "WEDDING_SUBCATEGORY_WEDDING_DECORATION": 300
        }